import {
    project0,
    project00,
    project1,
    project11,
    project2,
    project22,
    project3,
    project33,
    project4,
    project44,
    project5,
    project55,
    project6,
    project66,
    project7,
    project77,
    project8,
    project88,
    project9,
    project99,
    project10,
    project1010,
} from './projectImages';

export const projectData = [
    {
      id: 0,
      image: project0,
      transitionImage: project00,
      title: "Coinbase clon",
      codeLink: "https://github.com/martinmorondo/Clon-Coinbase",
      liveLink: "https://deluxe-froyo-29ea67.netlify.app/",
    },
    {
        id: 1,
        image: project1,
        transitionImage: project11,
        title: "Quiz App",
        codeLink: "https://github.com/martinmorondo/Quiz-app",
        liveLink: "https://fabulous-chebakia-16e5f0.netlify.app/",
      },
      {
        id: 2,
        image: project2,
        transitionImage: project22,
        title: "Whack a mole game",
        codeLink: "https://github.com/martinmorondo/Whack-a-mole-game",
        liveLink: "https://marvelous-lamington-597fcd.netlify.app/",
      },
      {
        id: 3,
        image: project3,
        transitionImage: project33,
        title: "Own Webpage",
        codeLink: "https://github.com/martinmorondo/My-website",
        liveLink: "https://recursosparaprogramadore5.ml/",
      },
      {
        id: 4,
        image: project4,
        transitionImage: project44,
        title: "JS Blender",
        codeLink: "https://github.com/martinmorondo/Licuadora-con-JS",
        liveLink: "https://startling-hummingbird-097d52.netlify.app",
      },
      {
        id: 5,
        image: project5,
        transitionImage: project55,
        title: "JS Puzzle",
        codeLink: "https://github.com/martinmorondo/Puzzle",
        liveLink: "https://magical-sprinkles-54dc75.netlify.app/",
      },
      {
        id: 6,
        image: project6,
        transitionImage: project66,
        title: "Movie App",
        codeLink: "https://scintillating-mooncake-f1005a.netlify.app",
        liveLink: "https://github.com/martinmorondo/movie-app",
      },
      {
        id: 7,
        image: project7,
        transitionImage: project77,
        title: "TODO App",
        codeLink: "https://github.com/martinmorondo/Lista-de-Tareas",
        liveLink: "https://fluffy-cocada-9c2f2e.netlify.app/",
      },
      {
        id: 8,
        image: project8,
        transitionImage: project88,
        title: "Poke App",
        codeLink: "https://github.com/martinmorondo/PokeApp",
        liveLink: "https://mellow-pasca-d188b5.netlify.app/",
      },
      {
        id: 9,
        image: project9,
        transitionImage: project99,
        title: "JS Ecommerce",
        codeLink: "https://github.com/martinmorondo/Ecommerce",
        liveLink: "https://mellifluous-cupcake-82cef1.netlify.app/",
      },
      {
        id: 10,
        image: project10,
        transitionImage: project1010,
        title: "React Weather App",
        codeLink: "https://github.com/martinmorondo/proyect-react-weatherApp",
        liveLink: "https://superlative-madeleine-ddfbfa.netlify.app/",
      },
]