import {
    project0,
    projectCero,
    project1,
    projectUno,
    project2,
    projectDos,
    project3,
    projectTres,
    project4,
    projectCuatro,
    project5,
    projectCinco,
    project6,
    projectSeis,
    project7,
    projectSiete,
    project8,
    projectOcho,
    project9,
    projectNueve,
    project10,
    projectDiez,
    project11,
    projectOnce,
    project12,
    projectDoce,
} from './projectImages';

export const projectData = [
    {
        id: 1,
        image: project0,
        transitionImage: projectCero,
        title: "Quiz App",
        codeLink: "https://github.com/martinmorondo/Quiz-app",
        liveLink: "https://fabulous-chebakia-16e5f0.netlify.app/",
      },
      {
        id: 2,
        image: project1,
        transitionImage: projectUno,
        title: "Whack a mole game",
        codeLink: "https://github.com/martinmorondo/Whack-a-mole-game",
        liveLink: "https://marvelous-lamington-597fcd.netlify.app/",
      },
      {
        id: 3,
        image: project2,
        transitionImage: projectTres,
        title: "Own Webpage",
        codeLink: "https://github.com/martinmorondo/My-website",
        liveLink: "https://recursosparaprogramadore5.ml/",
      },
      {
        id: 4,
        image: project3,
        transitionImage: projectTres,
        title: "JS Blender",
        codeLink: "https://github.com/martinmorondo/Licuadora-con-JS",
        liveLink: "https://startling-hummingbird-097d52.netlify.app",
      },
      {
        id: 5,
        image: project4,
        transitionImage: projectCuatro,
        title: "JS Puzzle",
        codeLink: "https://github.com/martinmorondo/Puzzle",
        liveLink: "https://magical-sprinkles-54dc75.netlify.app/",
      },
      {
        id: 6,
        image: project5,
        transitionImage: projectCinco,
        title: "Movie App",
        codeLink: "https://github.com/martinmorondo/movie-app",
        liveLink: "https://scintillating-mooncake-f1005a.netlify.app",
      },
      {
        id: 7,
        image: project6,
        transitionImage: projectSeis,
        title: "TODO App",
        codeLink: "https://github.com/martinmorondo/Lista-de-Tareas",
        liveLink: "https://fluffy-cocada-9c2f2e.netlify.app/",
      },
      {
        id: 8,
        image: project7,
        transitionImage: projectSiete,
        title: "Poke App",
        codeLink: "https://github.com/martinmorondo/PokeApp",
        liveLink: "https://mellow-pasca-d188b5.netlify.app/",
      },
      {
        id: 9,
        image: project8,
        transitionImage: projectOcho,
        title: "JS Ecommerce",
        codeLink: "https://github.com/martinmorondo/Ecommerce",
        liveLink: "https://mellifluous-cupcake-82cef1.netlify.app/",
      },
      {
        id: 10,
        image: project9,
        transitionImage: projectNueve,
        title: "React Weather App",
        codeLink: "https://github.com/martinmorondo/proyect-react-weatherApp",
        liveLink: "https://superlative-madeleine-ddfbfa.netlify.app/",
      },
      {
        id: 11,
        image: project10,
        transitionImage: projectDiez,
        title: "Twitter Follow Card",
        codeLink: "https://github.com/martinmorondo/react-twitter-follow-card",
        liveLink: "https://genuine-cajeta-a582bc.netlify.app/",
      },
      {
        id: 12,
        image: project11,
        transitionImage: projectOnce,
        title: "Tic Tac Toe Game",
        codeLink: "https://github.com/martinmorondo/tic-tac-toe-game",
        liveLink: "https://velvety-dragon-098b69.netlify.app/",
      },
      {
        id: 13,
        image: project12,
        transitionImage: projectDoce,
        title: "React Chatbot",
        codeLink: "https://github.com/martinmorondo/portfolio-chatbot",
        liveLink: "https://bucolic-praline-a0d151.netlify.app/",
      },
]